### ISSUE TITLE
game window is not proper. not able to see the bird

### ISSUE THREAD

**Issue by adibyte95** [ssusnic/Machine-Learning-Flappy-Bird#5]
![img](https://user-images.githubusercontent.com/12728710/37562347-d35ff9a6-2a8b-11e8-8e63-417b4dc0ebb3.png)

**Comment by Heimonen** [comment]
You need to run it through a web server. Navigate to the source folder and run:
```
npm install http-server -g
http-server
```
and surf to http://localhost:8080

**Comment by adibyte95** [comment]
done..
